[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_port = /dev/cu.usbmodem1302
monitor_speed = 115200

lib_deps =
    arduino-libraries/Arduino_GigaDisplayTouch@^1
    arduino-libraries/Arduino_BMI270_BMM150@^1
    lvgl/lvgl@^9

build_flags =
    -I../shared
    -Isrc
